app.service('MetaDataContainer', ['UserId', function(UserId) {
    this.data = [
    /*{
        label:"Advance Search",
        value:"AdvanceSearch",
        isSearchable:false,
        url:"https://"+window.location.host,
        menuname:"favourite",
        objectlevelaction:[
                               {name:"setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
                               {name:"console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"},
                               {name:"tce", actionUrl:"/ui/setup/apex/ApexTestQueuePage"},
                               {name:"jobs", actionUrl:"/08e"}
                           ]
    },*/
    {
        label:"View As",
        tooltipMessage:"View all users on salesforce",
        value:"ChangeUser",
        dataNotAvailableMessage:"Please click on view as to change user(No login required).",
        formainmenu:true,
        isSearchable:true,
        visibleForMetadataMenu:true,
        queryForAll:"select id, name, email, username from User where user.IsActive = true order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, Name, username, email from User where user.IsActive = true and name like ",
        url:"https://"+window.location.host+"/services/data/v32.0/query/?q=",
        imagesrc : chrome.extension.getURL("/img/icons/viewas.png"),
        url:"https://"+window.location.host+"/services/data/v42.0/query/?q=",
        placeholderText:"Search user...",
        type:"table",
        listUrl:"/005",
        midurl:"",
        eligibleForPackageXml:false,
        fieldlevelactions:[
                {name:"ChangeUser"}
                ],
        objectlevelaction:[
            {name:"setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"},
            {name:"Facebook Page", actionUrl:"https://www.fb.com/salesforcesimplified"}
            ]
    },{
        label:"Recently viewed",
        isSearchable:true,
        formainmenu:true,
        tooltipMessage:"Open home page",
        EligibleForAdvanceSearch:true,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not viewed any data in logged in org.",
        value:"RecentlyViewed",
        metadata:"RecentlyViewed",
        type:"table",
        listUrl:"/",
        menuname:"favourite",
        eligibleForPackageXml:false,
        query:"SELECT Id, Name, Type FROM RecentlyViewed WHERE Type IN ('ApexComponent', 'ApexPage', 'ApexTrigger', 'ApexClass', 'AssignmentRules', 'AuraDefinitionBundle', 'Bot', 'CustomApplication', 'CustomField', 'CustomLabel', 'CustomLabels', 'CustomObject', 'CustomPermission', 'CustomTab', 'Dashboard', 'Document', 'EmailTemplate', 'Flow', 'Group', 'HomePageComponent', 'ListView', 'Package', 'PermissionSet', 'Profile', 'Queue', 'RecordType', 'RemoteSiteSetting', 'Report', 'ReportType', 'Role', 'SharingRules', 'StaticResource', 'ValidationRule', 'WebLink', 'Workflow') ORDER BY LastViewedDate DESC",
        headers:["Log Size(byte)", "Operation", "Start Time"],
        objectlevelaction:[
            {name:"setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"},
            {name:"Facebook Page", actionUrl:"https://www.fb.com/salesforcesimplified"}
            ],
        url:"https://"+window.location.host+"/services/data/v43.0/tooling/query/?q=",
        fieldlevelactions:[{}],
        midurl:"",
        placeholderText:"Quick Search"
    },{
        label:"Debug logs",
        isSearchable:true,
        formainmenu:true,
        tooltipMessage:"View all logs on salesforce",
        EligibleForAdvanceSearch:true,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"Debug logs are not available for you, click on new to record debug logs.",
        value:"DebugLogs",
        metadata:"ApexLog",
        type:"table",
        eligibleForPackageXml:false,
        menuname:"favourite",
        queryForAll:"SELECT Id, LogUser.Name, LogLength, StartTime, Status, Operation, Location FROM ApexLog order by StartTime desc",
        queryForAllWithWhere:"SELECT Id, LogUser.Name, LogLength, StartTime, Status, Operation, Location FROM ApexLog where Operation like ",
        query:"SELECT Id, LogUser.Name, LogUserId, LogLength, LastModifiedDate, Request, Operation, Application, Status, DurationMilliseconds, SystemModstamp, StartTime, Location FROM ApexLog where LogUserId='"+UserId.id+"' order by StartTime desc",
        headers:["Log Size(byte)", "Operation", "Start Time"],
        objectlevelaction:[
            {name:"New", actionUrl:"https://"+window.location.host+"/udd/TraceFlag/editTraceFlag.apexp?logType=USER_DEBUG&retURL=%2Fsetup%2Fui%2FlistApexTraces.apexp"},
            {name:"setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"},
            {name:"Facebook Page", actionUrl:"https://www.fb.com/salesforcesimplified"}
            ],
        fieldlevelactions:[{}],
        url:"https://"+window.location.host+"/services/data/v32.0/query/?q=",
        listUrl:"/setup/ui/listApexTraces.apexp",
        midurl:"",
        imagesrc : chrome.extension.getURL("/img/icons/debuglogs.png"),
        placeholderText:"Search by size/operation/time/user..."
    },{
        label:"Classes",
        value:"Classes",
        isSearchable:true,
        formainmenu:true,
        tooltipMessage:"View all classes on salesforce",
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any class.",
        menuname:"favourite",
        queryForAll:"select id, name, ApiVersion, createdby.Name, NamespacePrefix, LastModifiedBy.Name from ApexClass order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, name, ApiVersion, createdby.Name, NamespacePrefix, LastModifiedBy.Name from ApexClass where name like ",
        query:"SELECT Id, Name, LastModifiedDate, LastModifiedBy.Id,  IsValid, ApiVersion, NamespacePrefix, CreatedBy.Name, LastModifiedBy.Name FROM ApexClass where  LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc",
        metadata:"ApexClass",
        imagesrc : chrome.extension.getURL("/img/icons/classes.png"),
        type:"table",
        headers:["Edit", "Download", "Name"],
        fieldlevelactions:[
                {name:"Edit", actionUrl:"/e"},
                {name:"Download", actionUrl:"/setup/apexcodedownload?class_id="},
                {name:"clsSecurity", actionUrl:"/_ui/perms/ui/profile/ApexClassProfilePermissionEdit/e?apex_id="}
                ],
        objectlevelaction:[
            {name:"New", actionUrl:"https://"+window.location.host+"/setup/build/editApexClass.apexp"},
            {name:"setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"},
            {name:"Generate WSDL", actionUrl:"/_ui/common/api/callout/ui/Wsdl2ApexStageManager"}, 
            {name:"Schedule Apex", actionUrl:"/ui/setup/apex/batch/ScheduleBatchApexPage"}],
            url:"https://"+window.location.host+"/services/data/v32.0/query/?q=",
        listUrl:"/01p",
        midurl:"",
        placeholderText:"Quick find/search class..."
    },{
        label:"Triggers",
        value:"Triggers",
        tooltipMessage:"View all triggers on salesforce",
        isSearchable:true,
        formainmenu:true,
        EligibleForAdvanceSearch:true,
        menuname:"favourite",
        eligibleForPackageXml:false,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any triggers.",
        queryForAll:"select id, name, ApiVersion, createdby.Name, NamespacePrefix, LastModifiedBy.Name from ApexTrigger order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, name, ApiVersion, createdby.Name, NamespacePrefix, LastModifiedBy.Name from ApexTrigger where name like ",
        query:"select id, Name, ApiVersion, createdby.name, LastModifiedDate, NamespacePrefix, LastModifiedBy.Name from ApexTrigger where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc ",
        metadata:"ApexTrigger",
        type:"table",
        headers:["Edit", "Download", "Name"],
        imagesrc : chrome.extension.getURL("/img/icons/triggers.png"),
        fieldlevelactions:[
                {name:"Edit", actionUrl:"/e"}, 
                {name:"Download", actionUrl:"/setup/apexcodedownload?class_id="}
                ],
        objectlevelaction:[
            {name:"setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"},
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"},
            {name:"Facebook Page", actionUrl:"https://www.fb.com/salesforcesimplified"}],
        url:"https://"+window.location.host+"/services/data/v32.0/query/?q=",
        listUrl:"/setup/build/allTriggers.apexp",
        midurl:"",
        placeholderText:"Quick find/search triggers..."
    },{
        label:"Aura Definition",
        value:"AuraDefinitionBundle",
        tooltipMessage:"Open Developer Console",
        isSearchable:true,
        formainmenu:true,
        eligibleForPackageXml:false,
        EligibleForAdvanceSearch:true,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any lightening components.",
        menuname:"favourite",
        queryForAll:"SELECT Id, DeveloperName, LastModifiedBy.Name, NamespacePrefix FROM AuraDefinitionBundle order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, DeveloperName, LastModifiedBy.Name, NamespacePrefix FROM AuraDefinitionBundle where DeveloperName like ",
        query:"SELECT Id, DeveloperName, LastModifiedBy.Name, NamespacePrefix FROM AuraDefinitionBundle where  LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc",
        metadata:"AuraDefinitionBundle",
        imagesrc : chrome.extension.getURL("/img/icons/AuraDefinitionBundles.png"),
        type:"table",
        headers:[],
        fieldlevelactions:[],
        objectlevelaction:[
                {name:"setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"},
                {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"},
                {name:"Facebook Page", actionUrl:"https://www.fb.com/salesforcesimplified"}
            ],
        url:"https://"+window.location.host+"/services/data/v32.0/query/?q=",
        listUrl:"/_ui/common/apex/debug/ApexCSIPage",
        midurl:"",
        placeholderText:"Quick find/search class..."
    },{
        label:"Pages",
        value:"Pages",
        tooltipMessage:"View all pages on salesforce",
        isSearchable:true,
        formainmenu:true,
        eligibleForPackageXml:false,
        EligibleForAdvanceSearch:true,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any visualforce pages.",
        menuname:"favourite",
        queryForAll:"select id, name, ApiVersion, createdby.Name, NamespacePrefix, LastModifiedBy.Name from ApexPage order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, name, ApiVersion, NamespacePrefix, createdby.Name, LastModifiedBy.Name from ApexPage where name like ",
        query:"select id, Name, ApiVersion, createdby.name, NamespacePrefix, LastModifiedDate, LastModifiedBy.Name from ApexPage where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc ",
        metadata:"ApexPage",
        type:"table",
        imagesrc : chrome.extension.getURL("/img/icons/pages.png"),
        headers:["Edit", "Security", "Name"],
        fieldlevelactions:[
                        {name:"Edit", actionUrl:"/e"},
                        {name:"Security", actionUrl:"&apex_name="}
                        ],
        objectlevelaction:[{name:"New", actionUrl:"https://"+window.location.host+"/066/e"}, 
	        {name:"setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
	        {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"},
	        {name:"Facebook Page", actionUrl:"https://www.fb.com/salesforcesimplified"}],
        url:"https://"+window.location.host+"/services/data/v42.0/tooling/query/?q=",
        listUrl:"/apexpages/setup/listApexPage.apexp",
        midurl:"",
        placeholderText:"Quick find/search pages..."
    },{
        label:"Components",
        value:"Components",
        tooltipMessage:"View all components on salesforce",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any visualforce components.",
        queryForAll:"select id, name, createdby.Name, NamespacePrefix, LastModifiedBy.Name from ApexComponent order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, name, createdby.Name, NamespacePrefix, LastModifiedBy.Name from ApexComponent where name like ",
        query:"select id, Name, createdby.name, LastModifiedDate, NamespacePrefix, LastModifiedBy.Name from ApexComponent where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc ",
        metadata:"ApexComponent",
        type:"table",
        headers:["Edit", "Name"],
        fieldlevelactions:[{name:"Edit", actionUrl:"/e"}],
        imagesrc : chrome.extension.getURL("/img/icons/components.png"),
        objectlevelaction:[{name:"New", actionUrl:"https://"+window.location.host+"/099/e"},
         {name:"setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
         {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"},
         {name:"Facebook Page", actionUrl:"https://www.fb.com/salesforcesimplified"}],
        url:"https://"+window.location.host+"/services/data/v42.0/tooling/query/?q=",
        listUrl:"/apexpages/setup/listApexComponent.apexp",
        midurl:"",
        placeholderText:"Quick find/search components..."
    },{
        label:"Objects",
        value:"Objects",
        tooltipMessage:"View all objects on salesforce",
        isSearchable:true,
        formainmenu:true,
        EligibleForAdvanceSearch:true,
        menuname:"favourite",
        eligibleForPackageXml:false,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any custom objects.",
        queryForAll:"select id, DeveloperName, ExternalName, createdby.Name, LastModifiedBy.Name, NamespacePrefix from CustomObject order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, DeveloperName, ExternalName, createdby.Name, NamespacePrefix, LastModifiedBy.Name from CustomObject where DeveloperName like ",
        query:"select id, DeveloperName, createdby.name, ExternalName, LastModifiedDate, NamespacePrefix, LastModifiedBy.Name from CustomObject where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc ",
        metadata:"CustomObjects",
        type:"table",
        headers:["Edit", "Name"],
        imagesrc : chrome.extension.getURL("/img/icons/objects.png"),
        fieldlevelactions:[
                {name:"Edit", actionUrl:"/e"}],
        objectlevelaction:[{name:"New", actionUrl:"https://"+window.location.host+"/01I/e"}, 
	        {name:"setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
	        {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"},
	        {name:"Facebook Page", actionUrl:"https://www.fb.com/salesforcesimplified"}],
        url:"https://"+window.location.host+"/services/data/v42.0/tooling/query/?q=",
        listUrl:"/p/setup/custent/CustomObjectsPage",
        midurl:"",
        placeholderText:"Quick find/search objects..."
    },{
        label:"Fields",
        value:"Fields",
        tooltipMessage:"View all objects on salesforce",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        menuname:"favourite",
        eligibleForPackageXml:false,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any custom fields.",
        queryForAll:"select id, DeveloperName, createdby.Name, TableEnumOrId, NamespacePrefix, LastModifiedBy.Name from CustomField order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, DeveloperName, createdby.Name, TableEnumOrId, NamespacePrefix, LastModifiedBy.Name from CustomField where DeveloperName like ",
        query:"select id, DeveloperName, createdby.name, LastModifiedDate, TableEnumOrId, NamespacePrefix, LastModifiedBy.Name from CustomField where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc ",
        metadata:"CustomFields",
        type:"table",
        imagesrc : chrome.extension.getURL("/img/icons/fields.png"),
        headers:["Edit", "Name"],
        fieldlevelactions:[
                {name:"Edit", actionUrl:"/e"}],
        objectlevelaction:[{name:"setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"},
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"},
            {name:"Facebook Page", actionUrl:"https://www.fb.com/salesforcesimplified"}
        ],
        url:"https://"+window.location.host+"/services/data/v42.0/tooling/query/?q=",
        listUrl:"/p/setup/custent/CustomObjectsPage",
        midurl:"",
        placeholderText:"Quick find/search fields..."
    },{
        label:"Labels",
        value:"Labels",
        tooltipMessage:"View all labels on salesforce",
        isSearchable:true,
        formainmenu:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any custom labels.",
        queryForAll:"select id, name, createdby.Name, LastModifiedBy.Name, NamespacePrefix from CustomLabel order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, name, createdby.Name, NamespacePrefix, LastModifiedBy.Name from CustomLabel where name like ",
        query:"select id, Name, createdby.name, LastModifiedDate, NamespacePrefix, LastModifiedBy.Name from CustomLabel where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc ",
        metadata:"CustomLabel",
        type:"table",
        headers:["Edit", "Name"],
        fieldlevelactions:[{name:"Edit", actionUrl:"/e"}],
        objectlevelaction:[{name:"New", actionUrl:"https://"+window.location.host+"/101/e"}, 
	        {name:"setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
	        {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"},
	        {name:"Facebook Page", actionUrl:"https://www.fb.com/salesforcesimplified"}],
        url:"https://"+window.location.host+"/services/data/v42.0/tooling/query/?q=",
        imagesrc : chrome.extension.getURL("/img/icons/labels.png"),
        listUrl:"/101",
        midurl:"",
        placeholderText:"Quick find/search labels..."
    },{
        label:"Workflows",
        value:"Workflows",
        tooltipMessage:"View all workflows on salesforce",
        queryForAll:"select id, name, createdby.Name, LastModifiedBy.Name from WorkflowRule order by LastModifiedDate desc",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any workflows.",
        queryForAllWithWhere:"select id, name, createdby.Name, NamespacePrefix, LastModifiedBy.Name from WorkflowRule where name like ",
        query:"select id, Name, createdby.name, LastModifiedDate, NamespacePrefix, LastModifiedBy.Name from WorkflowRule where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc ",
        metadata:"WorkflowRule",
        headers:["Edit", "Name"],
        type:"table",
        fieldlevelactions:[{name:"Edit", actionUrl:"/e"}, {name:"cloneWF", actionUrl:"/e"}],
        objectlevelaction:[{name:"New", actionUrl:"https://"+window.location.host+"/_ui/core/workflow/WorkflowSplashUi?EntityId=WorkflowRule&setupid=WorkflowRules"}, 
            {name:"setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"},
            {name:"Facebook Page", actionUrl:"https://www.fb.com/salesforcesimplified"}],
        url:"https://"+window.location.host+"/services/data/v42.0/tooling/query/?q=",
        listUrl:"/_ui/core/workflow/WorkflowSplashUi?EntityId=WorkflowRule",
        imagesrc : chrome.extension.getURL("/img/icons/workflows.png"),
        midurl:"",
        placeholderText:"Quick find/search workflow..."
    },{
        label:"Flows",
        value:"Flows",
        tooltipMessage:"View all flows on salesforce",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any flows.",
        queryForAll:"select id, DeveloperName, createdby.Name, NamespacePrefix, LastModifiedBy.Name from FlowDefinition order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, DeveloperName, createdby.Name, NamespacePrefix, LastModifiedBy.Name from FlowDefinition where DeveloperName like ",
        query:"select id, DeveloperName, createdby.name, LastModifiedDate, NamespacePrefix, LastModifiedBy.Name from FlowDefinition where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc ",
        metadata:"Flows",
        type:"table",
        headers:["Edit", "Name"],
        fieldlevelactions:[
                {name:"Edit", actionUrl:"/e"}
                ],
        objectlevelaction:[{name:"New", actionUrl:"https://"+window.location.host+"/designer/designer.apexp"}, 
            {name:"setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"},
            {name:"Facebook Page", actionUrl:"https://www.fb.com/salesforcesimplified"}],
        url:"https://"+window.location.host+"/services/data/v42.0/tooling/query/?q=",
        imagesrc : chrome.extension.getURL("/img/icons/flows.png"),
        listUrl:"/300",
        midurl:"",
        placeholderText:"Quick find/search flows..."
    },{
        label:"Email Templates",
        value:"EmailTemplates",
        tooltipMessage:"View all email templates on salesforce",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any email templates.",
        queryForAll:"select id, name, ApiVersion, createdby.Name, NamespacePrefix,  LastModifiedBy.Name from EmailTemplate order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, name, ApiVersion, createdby.Name, NamespacePrefix, LastModifiedBy.Name from EmailTemplate where name like ",
        query:"select id, Name, ApiVersion, createdby.name, LastModifiedDate, NamespacePrefix, LastModifiedBy.Name from EmailTemplate where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc ",
        metadata:"EmailTemplates",
        type:"table",
        imagesrc : chrome.extension.getURL("/img/icons/emailtemplates.png"),
        headers:["Edit", "Name"],
        fieldlevelactions:[
                {name:"Edit", actionUrl:"/e"}
                ],
        objectlevelaction:[{name:"New", actionUrl:"https://"+window.location.host+"/p/email/template/NewEmailTemplateStageManager?setupid=CommunicationTemplatesEmail"},
        {name:"setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"},
            {name:"Facebook Page", actionUrl:"https://www.fb.com/salesforcesimplified"}],
        url:"https://"+window.location.host+"/services/data/v42.0/tooling/query/?q=",
        listUrl:"/00X",
        midurl:"",
        placeholderText:"Quick find/search email template..."
    },{
        label:"Users",
        value:"Users",
        tooltipMessage:"View all users on salesforce",
        isSearchable:true,
        forAdvanceSearchOnly:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any users.",
        queryForAll:"select id, name, email, username, LastModifiedBy.Name from User where user.IsActive = true order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, name, email, username, LastModifiedBy.Name from User where user.IsActive = true and name like ",
        query:"select id, name, email, username, LastModifiedBy.Name from User where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc",
        metadata:"Users",
        type:"table",
        imagesrc : chrome.extension.getURL("/img/icons/users.png"),
        headers:["Edit", "Name"],
        fieldlevelactions:[
                {name:"Edit", actionUrl:"/e"}
                ],
        objectlevelaction:[{name:"New", actionUrl:"https://"+window.location.host+"/005/e"}, 
        {name:"setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"},
            {name:"Facebook Page", actionUrl:"https://www.fb.com/salesforcesimplified"}],
        url:"https://"+window.location.host+"/services/data/v42.0/query/?q=",
        listUrl:"/005",
        midurl:"",
        placeholderText:"Quick find/search Users..."
    },{
        label:"Static Resource",
        value:"StaticResource",
        tooltipMessage:"View all static resources on salesforce",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any static resource.",
        queryForAll:"select id, name, LastModifiedBy.Name, NamespacePrefix from StaticResource order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, name, NamespacePrefix, LastModifiedBy.Name from StaticResource where name like ",
        query:"select id, name, NamespacePrefix, LastModifiedBy.Name from StaticResource where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc",
        metadata:"StaticResource",
        type:"table",
        headers:["Edit", "Name"],
        imagesrc : chrome.extension.getURL("/img/icons/staticresource.png"),
        fieldlevelactions:[
                {name:"Edit", actionUrl:"/e"}
                ],
        objectlevelaction:[{name:"New", actionUrl:"https://"+window.location.host+"/081/e"},
        {name:"setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"},
            {name:"Facebook Page", actionUrl:"https://www.fb.com/salesforcesimplified"}],
        url:"https://"+window.location.host+"/services/data/v42.0/tooling/query/?q=",
        listUrl:"/081",
        midurl:"",
        placeholderText:"Quick find/search Resource..."
    },{
        label:"Profile",
        value:"Profile",
        tooltipMessage:"View all profiles on salesforce",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        visibleForMetadataMenu:true,
        eligibleForPackageXml:false,
        dataNotAvailableMessage:"You have not created/modified any profile.",
        queryForAll:"SELECT Id, Name, LastModifiedBy.name FROM Profile order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, Name, LastModifiedBy.name FROM Profile where name like ",
        query:"SELECT Id, Name, LastModifiedBy.name FROM Profile where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc",
        metadata:"Profile",
        type:"table",
        headers:["Edit", "Clone", "Name"],
        fieldlevelactions:[
                {name:"Edit", actionUrl:"/e"},
                {name:"Clone", actionUrl:"/_ui/perms/ui/profile/ProfileClone/e?id="}
                ],
        objectlevelaction:[{name:"New", actionUrl:"https://"+window.location.host+"/_ui/perms/ui/profile/ProfileClone/e"},
        {name:"setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"},
            {name:"Facebook Page", actionUrl:"https://www.fb.com/salesforcesimplified"}],
        url:"https://"+window.location.host+"/services/data/v42.0/query/?q=",
        listUrl:"/00e",
        midurl:"",
        placeholderText:"Quick find/search Profile..."
    },{
        label:"Group",
        value:"Group",
        tooltipMessage:"View all groups on salesforce",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        dataNotAvailableMessage:"You have not created/modified any group.",
        queryForAll:"SELECT Id, DeveloperName, LastModifiedBy.name FROM Group order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, DeveloperName, LastModifiedBy.name FROM Group where DeveloperName like ",
        query:"SELECT Id, DeveloperName, LastModifiedBy.name FROM Group where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc",
        metadata:"Group",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        fieldlevelactions:[{}],
        midurl:"setup/own/groupdetail.jsp?id=",
        objectlevelaction:[{name:"New", actionUrl:"https://"+window.location.host+"/setup/own/groupedit.jsp"},
        {name:"setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"},
            {name:"Facebook Page", actionUrl:"https://www.fb.com/salesforcesimplified"}],
        url:"https://"+window.location.host+"/services/data/v42.0/query/?q=",
        listUrl:"/p/own/OrgPublicGroupsPage/d",
        midurl:"setup/own/groupdetail.jsp?id=",
        placeholderText:"Quick find/search Group..."
    },/*{
        label:"Coverage",
        value:"ApexCodeCoverageAggregate",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        dataNotAvailableMessage:"Coverage show you real time code coverage of your current your.",
        queryForAll:"SELECT Id,createdDate, ApexClassorTrigger.Name,ApexClassorTriggerId,NumLinesCovered,NumLinesUncovered,Coverage FROM ApexCodeCoverageAggregate Order By CreatedDate DESC",
        metadata:"ApexCodeCoverageAggregate",
        type:"table",
        imagesrc : chrome.extension.getURL("/img/icons/coverages.png"),
        url:"https://"+window.location.host+"/services/data/v42.0/tooling/query/?q=",
        forAdvanceSearchOnly:true,
        placeholderText:"Quick find/search Coverage..."
    },{
        label:"Settings",
        value:"Settings",
        isSearchable:false,
        url:"",
        menuname:"favourite",
        objectlevelaction:[
                               {name:"User", actionUrl:""}, 
                               {name:"Favourite", actionUrl:""}
                           ]
    },*/{
        label:"Package.xml",
        value:"PackageXml",
        tooltipMessage:"Open home page",
        isSearchable:false,
        eligibleForPackageXml:false,
        visibleForMetadataMenu:false,
        url:"https://"+window.location.host+"/services/data/v42.0/tooling/query/?q=",
        midurl:"",
        listUrl:"/",
        fieldlevelactions:[{}],
        objectlevelaction:[
                               {name:"Facebook Page", actionUrl:"https://www.fb.com/salesforcesimplified"},
                               {name:"Contribute", actionUrl:"https://github.com/rajnikantroy/Salesforce-Simplified"}
                           ]
    },{
        label:"RecordType",
        value:"RecordType",
        tooltipMessage:"Go to home page",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        isSobjectType:true,
        dataNotAvailableMessage:"You have not created/modified any Record Type.",
        queryForAll:"SELECT Id, SobjectType, DeveloperName, LastModifiedBy.name FROM RecordType order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, SobjectType, DeveloperName, LastModifiedBy.name FROM RecordType where DeveloperName like ",
        query:"SELECT Id, DeveloperName, SobjectType, LastModifiedBy.name FROM RecordType where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc",
        metadata:"RecordType",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        fieldlevelactions:[{name:"Edit", actionUrl:"/setup/ui/recordtypeedit.jsp?id="}],
        objectlevelaction:[{name:"setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"},
            {name:"Facebook Page", actionUrl:"https://www.fb.com/salesforcesimplified"}],
        url:"https://"+window.location.host+"/services/data/v42.0/query/?q=",
        midurl:"setup/ui/recordtypefields.jsp?id=",
        listUrl:"/",
        placeholderText:"Quick find/search Group..."
    },{
        label:"Layout",
        value:"Layout",
        tooltipMessage:"Go to home page",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        isSobjectType:true,
        dataNotAvailableMessage:"You have not created/modified any Layout",
        queryForAll:"SELECT Id, TableEnumOrId, Name, LastModifiedBy.name FROM Layout order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, TableEnumOrId, Name, LastModifiedBy.name FROM Layout where DeveloperName like ",
        query:"SELECT Id, TableEnumOrId, Name, LastModifiedBy.name FROM Layout where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc",
        metadata:"RecordType",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        fieldlevelactions:[],
        objectlevelaction:[{name:"setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"},
            {name:"Facebook Page", actionUrl:"https://www.fb.com/salesforcesimplified"}],
        url:"https://"+window.location.host+"/services/data/v42.0/tooling/query/?q=",
        midurl:"",
        listUrl:"/",
        placeholderText:"Quick find/search Group..."
    },{
        label:"AssignmentRule",
        value:"AssignmentRule",
        tooltipMessage:"Go to home page",
        isSearchable:true,
        isSobjectType:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        dataNotAvailableMessage:"You have not created/modified any Assignment rules.",
        queryForAll:"SELECT Id, Name, SobjectType, LastModifiedBy.name FROM AssignmentRule order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, Name, SobjectType, LastModifiedBy.name FROM AssignmentRule where DeveloperName like ",
        query:"SELECT Id, Name, SobjectType, LastModifiedBy.name FROM AssignmentRule where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc",
        metadata:"AssignmentRule",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        fieldlevelactions:[{name:"Edit", actionUrl:"/setup/own/entityruleedit.jsp?id="}],
        objectlevelaction:[{name:"setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"},
            {name:"Facebook Page", actionUrl:"https://www.fb.com/salesforcesimplified"}],
        url:"https://"+window.location.host+"/services/data/v42.0/query/?q=",
        midurl:"setup/own/entityruledetail.jsp?id=",
        listUrl:"/",
        placeholderText:"Quick find/search Group..."
    },{
        label:"WebLink",
        value:"WebLink",
        tooltipMessage:"Go to home page",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        isSobjectType:true,
        dataNotAvailableMessage:"You have not created/modified any Weblink.",
        queryForAll:"SELECT Id, Name, NamespacePrefix, LastModifiedBy.name FROM WebLink order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, Name, NamespacePrefix, LastModifiedBy.name FROM WebLink where DeveloperName like ",
        query:"SELECT Id, Name, LastModifiedBy.name, NamespacePrefix FROM WebLink where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc",
        metadata:"WebLink",
        type:"table",
        visibleForMetadataMenu:true,
        midurl:"",
        headers:["Edit", "Name"],
        fieldlevelactions:[{name:"Edit", actionUrl:"/e"}],
        objectlevelaction:[{name:"setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"},
            {name:"Facebook Page", actionUrl:"https://www.fb.com/salesforcesimplified"}],
        url:"https://"+window.location.host+"/services/data/v42.0/query/?q=",
        listUrl:"/",
        placeholderText:"Quick find/search Group..."
    },{
        label:"ListView",
        value:"ListView",
        tooltipMessage:"Go to home page",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        isSobjectType:true,
        dataNotAvailableMessage:"You have not created/modified any Listview.",
        queryForAll:"SELECT Id, DeveloperName, SobjectType, NamespacePrefix, LastModifiedBy.name FROM ListView order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, SobjectType, DeveloperName, NamespacePrefix, LastModifiedBy.name FROM ListView where DeveloperName like ",
        query:"SELECT Id, DeveloperName, SobjectType, LastModifiedBy.name, NamespacePrefix FROM ListView where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc",
        metadata:"WebLink",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        midurl:"",
        fieldlevelactions:[{}],
        objectlevelaction:[{name:"setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"},
            {name:"Facebook Page", actionUrl:"https://www.fb.com/salesforcesimplified"}
            ],
        url:"https://"+window.location.host+"/services/data/v42.0/query/?q=",
        listUrl:"/",
        placeholderText:"Quick find/search Group..."
    }/*,{
        label:"About",
        value:"About",
        tooltipMessage:"Open home page",
        formainmenu:true,
        isSearchable:false,
        visibleForMetadataMenu:true,
        eligibleForPackageXml:false,
        url:"",
        listUrl:"/",
        fieldlevelactions:[{}],
        objectlevelaction:[
                               {name:"Linkedin", actionUrl:"https://www.linkedin.com/in/rajnikantroy/"}, 
                               {name:"Facebook Page", actionUrl:"https://www.fb.com/salesforcesimplified"},
                               {name:"GitHub", actionUrl:"https://github.com/rajnikantroy/Salesforce-Simplified"},
                               {name:"Donate", actionUrl:"https://www.paypal.me/rajnikantroy"}
                           ]
    }*/,{
        label:"FAQ",
        value:"Faq",
        tooltipMessage:"Open home page",
        isSearchable:false,
        eligibleForPackageXml:false,
        url:"",
        visibleForMetadataMenu:true,
        listUrl:"/",
        fieldlevelactions:[{}],
        objectlevelaction:[
                               {name:"Linkedin", actionUrl:"https://www.linkedin.com/in/rajnikantroy/"}, 
                               {name:"Facebook Page", actionUrl:"https://www.fb.com/salesforcesimplified"},
                               {name:"GitHub", actionUrl:"https://github.com/rajnikantroy/Salesforce-Simplified"}
                           ]
    }];

}]);