app.service('MetaDataContainer', ['UserId',  function(UserId) {
    this.data = [
    {
        label:"View As",
        tooltipMessage:"View all users on salesforce",
        value:"ChangeUser",
		technologyFeature:"Settings",
        dataNotAvailableMessage:"Please click on view as to change user(No login required).",
        formainmenu:true,
        isSearchable:true,
        visibleForMetadataMenu:true,
        visibleForMetadataIconMenu:true,
        queryForAll:"select id, name, email, username from User where IsActive = true order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, Name, username, email from User where IsActive = true and name like ",
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        imagesrc : chrome.runtime.getURL("/img/icons/viewas.png"),
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        placeholderText:"Search user...",
        type:"table",
        listUrl:"/005",
        midurl:"",
        eligibleForPackageXml:false,
        fieldlevelactions:[
                {name:"ChangeUser"}
                ],
        objectlevelaction:[
            {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
            ]
    },{
        label:"Recently viewed",
        isSearchable:true,
        formainmenu:true,
		technologyFeature:"Settings",
        tooltipMessage:"Open home page",
        EligibleForAdvanceSearch:true,
        visibleForMetadataMenu:true,
        visibleForMetadataIconMenu:true,
        dataNotAvailableMessage:"You have not viewed any data in logged in org.",
        value:"RecentlyViewed",
        metadata:"RecentlyViewed",
        type:"table",
        listUrl:"/",
        menuname:"favourite",
        eligibleForPackageXml:false,
        query:"SELECT Id, Name, Type FROM RecentlyViewed WHERE Type IN ('User', 'ApexComponent', 'ApexPage', 'ApexTrigger', 'ApexClass', 'AssignmentRules', 'AuraDefinitionBundle', 'Bot', 'CustomApplication', 'CustomField', 'CustomLabel', 'CustomLabels', 'CustomObject', 'CustomPermission', 'CustomTab', 'Dashboard', 'Document', 'EmailTemplate', 'Flow', 'Group', 'HomePageComponent', 'Package', 'PermissionSet', 'Profile', 'Queue', 'RemoteSiteSetting', 'Report', 'Role', 'SharingRules', 'StaticResource', 'ValidationRule', 'WebLink', 'Workflow') ORDER BY LastViewedDate DESC",
        headers:["Log Size(byte)", "Operation", "Start Time"],
        objectlevelaction:[
            {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v43.0/tooling/query/?q=",
        fieldlevelactions:[{}],
        midurl:"",
        placeholderText:"Quick Search"
    },{
        label:"Debug logs",
        isSearchable:true,
        formainmenu:true,
		technologyFeature:"Settings",
        tooltipMessage:"View all logs on salesforce",
        EligibleForAdvanceSearch:true,
        visibleForMetadataMenu:true,
        visibleForMetadataIconMenu:true,
        dataNotAvailableMessage:"Debug logs are not available for you, click on new to record debug logs.",
        value:"DebugLogs",
        metadata:"ApexLog",
        type:"table",
        eligibleForPackageXml:false,
        menuname:"favourite",
        queryForAll:"SELECT Id, LogUser.Name, LogLength, StartTime, Status, Operation, Location FROM ApexLog order by StartTime desc",
        queryForAllWithWhere:"SELECT Id, LogUser.Name, LogLength, StartTime, Status, Operation, Location FROM ApexLog where Operation like ",
        query:"SELECT Id, LogUser.Name, LogUserId, LogLength, LastModifiedDate, Request, Operation, Application, Status, DurationMilliseconds, SystemModstamp, StartTime, Location FROM ApexLog where LogUserId='"+UserId.id+"' order by StartTime desc",
        headers:["Log Size(byte)", "Operation", "Start Time"],
        objectlevelaction:[
            {name:"New", actionUrl:"https://"+window.location.host+"/udd/TraceFlag/editTraceFlag.apexp?logType=USER_DEBUG&retURL=%2Fsetup%2Fui%2FlistApexTraces.apexp"},
            {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
            
            ],
        fieldlevelactions:[{}],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/setup/ui/listApexTraces.apexp",
        midurl:"",
        imagesrc : chrome.runtime.getURL("/img/icons/debuglogs.png"),
        placeholderText:"Search by size/operation/time/user..."
    },{
        label:"Campaigns",
        value:"Campaign",
        tooltipMessage:"View all campaign on salesforce",
        isSearchable:true,
        formainmenu:true,
		technologyFeature:"Admin",
        isAdminComponent:true,
        EligibleForAdvanceSearch:true,
        dataNotAvailableMessage:"You have not created/modified any campaign.",
        queryForAll:"SELECT Id, Name, Status,LastModifiedBy.name FROM Campaign order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, Status,Name, LastModifiedBy.name FROM Campaign where Name like ",
        query:"SELECT Id, Name, Status,LastModifiedBy.name FROM Campaign where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc",
        metadata:"Campaign",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        midurl:"",
        fieldlevelactions:[{name:"ViewEye"}, {name:"Edit", actionUrl:"/e"}],
        objectlevelaction:[
            {name:"New", actionUrl:"https://"+window.location.host+"/701/e"},
            {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"All Tabs", actionUrl:"/home/showAllTabs.jsp"},
            {name:"Chatter", actionUrl:"/_ui/core/chatter/ui/ChatterPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/701/o",
        midurl:"",
        placeholderText:"Quick find/search Campaigns..."
    },{
        label:"Leads",
        value:"Lead",
        tooltipMessage:"View all lead on salesforce",
        isSearchable:true,
        isAdminComponent:true,
        formainmenu:true,
		technologyFeature:"Admin",
        EligibleForAdvanceSearch:true,
        dataNotAvailableMessage:"You have not created/modified any lead.",
        queryForAll:"SELECT Id, Name, Status,LastModifiedBy.name FROM Lead order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id,Status, Name, LastModifiedBy.name FROM Lead where Name like ",
        query:"SELECT Id, Name, Status,LastModifiedBy.name FROM Lead where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc",
        metadata:"Lead",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        midurl:"",
        fieldlevelactions:[{name:"ViewEye"}, {name:"Edit", actionUrl:"/e"}],
        objectlevelaction:[
            {name:"New", actionUrl:"https://"+window.location.host+"/00Q/e"},
            {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"All Tabs", actionUrl:"/home/showAllTabs.jsp"},
            {name:"Chatter", actionUrl:"/_ui/core/chatter/ui/ChatterPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/00Q/o",
        midurl:"",
        placeholderText:"Quick find/search Lead by status etc..."
    },{
        label:"Accounts",
        value:"Account",
        tooltipMessage:"View all accounts on salesforce",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        isAdminComponent:true,
        formainmenu:true,
		technologyFeature:"Admin",
        dataNotAvailableMessage:"You have not created/modified any accounts.",
        queryForAll:"SELECT Id, Name, LastModifiedBy.name FROM Account order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, Name, LastModifiedBy.name FROM Account where Name like ",
        query:"SELECT Id, Name,LastModifiedBy.name FROM Account where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc",
        metadata:"Account",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        midurl:"",
        fieldlevelactions:[{name:"ViewEye"}, {name:"Edit", actionUrl:"/e"}],
        objectlevelaction:[
            {name:"New", actionUrl:"https://"+window.location.host+"/001/e"},
            {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"All Tabs", actionUrl:"/home/showAllTabs.jsp"},
            {name:"Chatter", actionUrl:"/_ui/core/chatter/ui/ChatterPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/001/o",
        midurl:"",
        placeholderText:"Quick find/search Account Name etc..."
    },{
        label:"Contacts",
        value:"Contact",
        tooltipMessage:"View all contact on salesforce",
        isSearchable:true,
        formainmenu:true,
        isAdminComponent:true,
		technologyFeature:"Admin",
        EligibleForAdvanceSearch:true,
        dataNotAvailableMessage:"You have not created/modified any contact.",
        queryForAll:"SELECT Id, Name, LastModifiedBy.name FROM Contact order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, Name, LastModifiedBy.name FROM Contact where Name like ",
        query:"SELECT Id, Name, LastModifiedBy.name FROM Contact where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc",
        metadata:"Contact",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        midurl:"",
        fieldlevelactions:[{name:"ViewEye"}, {name:"Edit", actionUrl:"/e"}],
        objectlevelaction:[
            {name:"New", actionUrl:"https://"+window.location.host+"/003/e"},
            {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"All Tabs", actionUrl:"/home/showAllTabs.jsp"},
            {name:"Chatter", actionUrl:"/_ui/core/chatter/ui/ChatterPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/003/o",
        midurl:"",
        placeholderText:"Quick find/Search Contacts by Name type etc..."
    },{
        label:"Opportunities",
        value:"Opportunity",
        tooltipMessage:"View all opportunity on salesforce",
        isSearchable:true,
        formainmenu:true,
        isAdminComponent:true,
		technologyFeature:"Admin",
        EligibleForAdvanceSearch:true,
        dataNotAvailableMessage:"You have not created/modified any opportunity.",
        queryForAll:"SELECT Id, Name,StageName,LastModifiedBy.name FROM Opportunity order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id,StageName, Name, LastModifiedBy.name FROM Opportunity where Name like ",
        query:"SELECT Id, Name,StageName, LastModifiedBy.name FROM Opportunity where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc",
        metadata:"Opportunity",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        midurl:"",
        fieldlevelactions:[{name:"ViewEye"}, {name:"Edit", actionUrl:"/e"}],
        objectlevelaction:[
            {name:"New", actionUrl:"https://"+window.location.host+"/006/e"},
            {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"All Tabs", actionUrl:"/home/showAllTabs.jsp"},
            {name:"Chatter", actionUrl:"/_ui/core/chatter/ui/ChatterPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/006/o",
        midurl:"",
        placeholderText:"Quick find/Search opportunity by stagename etc..."
    },{
        label:"Quotes",
        value:"Quote",
        tooltipMessage:"View all quotes on salesforce",
        isSearchable:true,
        formainmenu:true,
        isAdminComponent:true,
		technologyFeature:"Admin",
        EligibleForAdvanceSearch:true,
        dataNotAvailableMessage:"You have not created/modified any quote.",
        queryForAll:"SELECT Id, Name,Status,LastModifiedBy.name FROM Quote order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id,Status, Name, LastModifiedBy.name FROM Quote where Name like ",
        query:"SELECT Id, Name,Status,LastModifiedBy.name FROM Quote where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc",
        metadata:"Quote",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        fieldlevelactions:[{}],
        midurl:"",
        fieldlevelactions:[{name:"ViewEye"}, {name:"Edit", actionUrl:"/e"}],
        objectlevelaction:[
            {name:"All Quote", actionUrl:"/0Q0/o"},
            {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"All Tabs", actionUrl:"/home/showAllTabs.jsp"},
            {name:"Chatter", actionUrl:"/_ui/core/chatter/ui/ChatterPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/0Q0/o",
        midurl:"",
        placeholderText:"Quick find/search Qoute by status etc..."
    },{
        label:"Contracts",
        value:"Contract",
        tooltipMessage:"View all contracts on salesforce",
        isSearchable:true,
        formainmenu:true,
        isAdminComponent:true,
		technologyFeature:"Admin",
        EligibleForAdvanceSearch:true,
        dataNotAvailableMessage:"You have not created/modified any contract.",
        queryForAll:"SELECT Id, Status, ContractNumber, LastModifiedBy.name FROM Contract order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id,Status,ContractNumber, LastModifiedBy.name FROM Contract where Name like ",
        query:"SELECT Id, ContractNumber, Status,LastModifiedBy.name FROM Contract where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc",
        metadata:"Contract",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        fieldlevelactions:[{}],
        midurl:"",
        fieldlevelactions:[
            {name:"ViewEye"}, 
            {name:"Edit", actionUrl:"/e"}
            ],
        objectlevelaction:[
            {name:"New", actionUrl:"https://"+window.location.host+"/800/e"},
            {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"All Tabs", actionUrl:"/home/showAllTabs.jsp"},
            {name:"Chatter", actionUrl:"/_ui/core/chatter/ui/ChatterPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/800/o",
        midurl:"",
        placeholderText:"Quick find/Search Contract by status etc..."
    },{
        label:"Cases",
        value:"Case",
        tooltipMessage:"View all cases on salesforce",
        isSearchable:true,
        isAdminComponent:true,
		technologyFeature:"Admin",
        EligibleForAdvanceSearch:true,
        dataNotAvailableMessage:"You have not created/modified any cases.",
        queryForAll:"SELECT Id, CaseNumber,Status, LastModifiedBy.name FROM Case order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, Status,CaseNumber, LastModifiedBy.name FROM Case where Name like ",
        query:"SELECT Id, CaseNumber, Status,LastModifiedBy.name FROM Case where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc",
        metadata:"Case",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        midurl:"",
        fieldlevelactions:[{name:"ViewEye"}, {name:"Edit", actionUrl:"/e"}],
        objectlevelaction:[
            {name:"New", actionUrl:"https://"+window.location.host+"/500/e"},
            {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"All Tabs", actionUrl:"/home/showAllTabs.jsp"},
            {name:"Chatter", actionUrl:"/_ui/core/chatter/ui/ChatterPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/500/o",
        midurl:"",
        placeholderText:"Quick find/Search Case by status etc..."
    },{
        label:"Orders",
        value:"Order",
        tooltipMessage:"View all orders on salesforce",
        isSearchable:true,
        isAdminComponent:true,
		technologyFeature:"Admin",
        EligibleForAdvanceSearch:true,
        dataNotAvailableMessage:"You have not created/modified any order.",
        queryForAll:"SELECT Id, OrderNumber, Status,LastModifiedBy.name FROM Order order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, Status,OrderNumber, LastModifiedBy.name FROM Order where Name like ",
        query:"SELECT Id, OrderNumber, Status,LastModifiedBy.name FROM Order where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc",
        metadata:"Order",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        fieldlevelactions:[{}],
        midurl:"",
        fieldlevelactions:[{name:"ViewEye"}, {name:"Edit", actionUrl:"/e"}],
        objectlevelaction:[
            {name:"New", actionUrl:"https://"+window.location.host+"/801/e"},
            {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"All Tabs", actionUrl:"/home/showAllTabs.jsp"},
            {name:"Chatter", actionUrl:"/_ui/core/chatter/ui/ChatterPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/801/o",
        midurl:"",
        placeholderText:"Quick find/Search Order by status etc..."
    },{
        label:"Reports",
        value:"Report",
        tooltipMessage:"View all reports on salesforce",
        isSearchable:true,
        isAdminComponent:true,
		technologyFeature:"Admin",
        EligibleForAdvanceSearch:true,
        dataNotAvailableMessage:"You have not created/modified any report.",
        queryForAll:"SELECT Id, Name, FolderName, LastModifiedBy.name FROM Report order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, Name, FolderName, LastModifiedBy.name FROM Report where Name like ",
        query:"SELECT Id, Name, FolderName, LastModifiedBy.name FROM Report where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc",
        metadata:"Report",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        fieldlevelactions:[{}],
        midurl:"",
        fieldlevelactions:[
            {name:"ViewEye"}, 
            {name:"Edit", actionUrl:"/e"}
            ],
        objectlevelaction:[
            {name:"New", actionUrl:"https://"+window.location.host+"/00O/e"},
            {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"All Tabs", actionUrl:"/home/showAllTabs.jsp"},
            {name:"Chatter", actionUrl:"/_ui/core/chatter/ui/ChatterPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/00O/o",
        midurl:"",
        placeholderText:"Quick find/search Reports..."
    },{
        label:"Dashboards",
        value:"Dashboard",
        tooltipMessage:"View all dashboards on salesforce",
        isSearchable:true,
        isAdminComponent:true,
		technologyFeature:"Admin",
        EligibleForAdvanceSearch:true,
        dataNotAvailableMessage:"You have not created/modified any dashboard.",
        queryForAll:"SELECT Id, DeveloperName, LastModifiedBy.name FROM Dashboard order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, DeveloperName, LastModifiedBy.name FROM Dashboard where Name like ",
        query:"SELECT Id, DeveloperName, LastModifiedBy.name FROM Dashboard where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc",
        metadata:"Dashboard",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        fieldlevelactions:[{}],
        midurl:"",
        fieldlevelactions:[
            {name:"ViewEye"}, 
            {name:"Edit", actionUrl:"/e"}
            ],
        objectlevelaction:[
            {name:"New", actionUrl:"https://"+window.location.host+"/01Z/e"},
            {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"All Tabs", actionUrl:"/home/showAllTabs.jsp"},
            {name:"Chatter", actionUrl:"/_ui/core/chatter/ui/ChatterPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/01Z/o",
        midurl:"",
        placeholderText:"Quick find/search Group..."
    },{
        label:"Assets",
        value:"Asset",
        tooltipMessage:"View all assets on salesforce",
        isSearchable:true,
        isAdminComponent:true,
		technologyFeature:"Admin",
        EligibleForAdvanceSearch:true,
        dataNotAvailableMessage:"You have not created/modified any asset.",
        queryForAll:"SELECT Id, Name, Status, LastModifiedBy.name FROM Asset order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, Name, Status, LastModifiedBy.name FROM Asset where Name like ",
        query:"SELECT Id, Name, Status, LastModifiedBy.name FROM Asset where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc",
        metadata:"Asset",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        fieldlevelactions:[{}],
        midurl:"",
        fieldlevelactions:[
            {name:"ViewEye"}, 
            {name:"Edit", actionUrl:"/e"}
            ],
        objectlevelaction:[
            {name:"New", actionUrl:"https://"+window.location.host+"/02i/e"},
            {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"All Tabs", actionUrl:"/home/showAllTabs.jsp"},
            {name:"Chatter", actionUrl:"/_ui/core/chatter/ui/ChatterPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/02i/o",
        midurl:"",
        placeholderText:"Quick find/search Group..."
    },{
        label:"Omniscript",
        value:"OmniScript__c",
        isSearchable:true,
		technologyFeature:"Vlocity",
        formainmenu:true,
        tooltipMessage:"View all Omniscript",
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        visibleForMetadataMenu:Boolean(readCookie('isNamespacePrefixAvailable')), 
        visibleForMetadataIconMenu:Boolean(readCookie('isNamespacePrefixAvailable')),
        dataNotAvailableMessage:"You have not created/modified any Vlocity Omniscript.",
        menuname:"favourite",
        queryForAll:"select id, "+readCookie('NamespacePrefix')+"IsActive__c, "+readCookie('NamespacePrefix')+"Version__c, name, createdby.Name, LastModifiedBy.Name from "+readCookie('NamespacePrefix')+"OmniScript__c WHERE "+readCookie('NamespacePrefix')+"OmniProcessType__c = 'OmniScript'  order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, "+readCookie('NamespacePrefix')+"IsActive__c, "+readCookie('NamespacePrefix')+"Version__c, name, createdby.Name, LastModifiedBy.Name from "+readCookie('NamespacePrefix')+"OmniScript__c where "+readCookie('NamespacePrefix')+"OmniProcessType__c = 'OmniScript' AND Name like ",
        query:"SELECT Id, "+readCookie('NamespacePrefix')+"IsActive__c, "+readCookie('NamespacePrefix')+"Version__c, Name, LastModifiedDate, LastModifiedBy.Id, CreatedBy.Name, LastModifiedBy.Name FROM "+readCookie('NamespacePrefix')+"OmniScript__c where (LastModifiedById='"+UserId.id+"' OR CreatedById='"+UserId.id+"') AND "+readCookie('NamespacePrefix')+"OmniProcessType__c = 'OmniScript' order by LastModifiedDate desc",
        metadata:"OmniScript__c",
        imagesrc : chrome.runtime.getURL("/img/icons/classes.png"),
        type:"table",
        headers:["Edit", "Download", "Name"],
        fieldlevelactions:[{name:"ViewEye"}],
        objectlevelaction:[
            {name:"New", actionUrl:"/apex/"+readCookie('NamespacePrefix')+"omniscriptdesigner"},
            {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}],
            url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/apex/"+readCookie('NamespacePrefix')+"omniscripthome",
        midurl:"/apex/"+readCookie('NamespacePrefix')+"omniscriptdesigner?id=",
        placeholderText:"Quick find/search Omniscript..."
    },{
        label:"Integration Procedure",
        value:"OmniScript__c",
        isSearchable:true,
		technologyFeature:"Vlocity",
        formainmenu:false,
        tooltipMessage:"View all Integration Procedure",
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
        visibleForMetadataMenu:Boolean(readCookie('isNamespacePrefixAvailable')), 
        visibleForMetadataIconMenu:Boolean(readCookie('isNamespacePrefixAvailable')),
        dataNotAvailableMessage:"You have not created/modified any Vlocity Integration Procedure.",
        menuname:"favourite",
        queryForAll:"select id, "+readCookie('NamespacePrefix')+"IsActive__c, "+readCookie('NamespacePrefix')+"Version__c, name, createdby.Name, LastModifiedBy.Name from "+readCookie('NamespacePrefix')+"OmniScript__c  where "+readCookie('NamespacePrefix')+"OmniProcessType__c = 'Integration Procedure' order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, "+readCookie('NamespacePrefix')+"IsActive__c, "+readCookie('NamespacePrefix')+"Version__c, name, createdby.Name, LastModifiedBy.Name from "+readCookie('NamespacePrefix')+"OmniScript__c where "+readCookie('NamespacePrefix')+"OmniProcessType__c = 'Integration Procedure' AND name like ",
        query:"SELECT Id, "+readCookie('NamespacePrefix')+"IsActive__c, "+readCookie('NamespacePrefix')+"Version__c, Name, LastModifiedDate, LastModifiedBy.Id, CreatedBy.Name, LastModifiedBy.Name FROM "+readCookie('NamespacePrefix')+"OmniScript__c where (LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"') AND "+readCookie('NamespacePrefix')+"OmniProcessType__c = 'Integration Procedure' order by LastModifiedDate desc",
        metadata:"OmniScript__c",
        imagesrc : chrome.runtime.getURL("/img/icons/classes.png"),
        type:"table",
        headers:["Edit", "Download", "Name"],
        fieldlevelactions:[{name:"ViewEye"}],
        objectlevelaction:[
            {name:"New", actionUrl:"/apex/"+readCookie('NamespacePrefix')+"integrationproceduredesigner"},
            {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}],
            url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/apex/"+readCookie('NamespacePrefix')+"integrationprocedurehome",
        midurl:"/apex/"+readCookie('NamespacePrefix')+"integrationproceduredesigner?id=",
        placeholderText:"Quick find/search Integration Procedures..."
    },{
        label:"Templates",
        value:"VlocityUITemplate__c",
        tooltipMessage:"View all Templates",
        isSearchable:true,
        formainmenu:true,
		technologyFeature:"Vlocity",
        EligibleForAdvanceSearch:true,
        menuname:"favourite",
        eligibleForPackageXml:false,
        visibleForMetadataMenu:Boolean(readCookie('isNamespacePrefixAvailable')),
        visibleForMetadataIconMenu:Boolean(readCookie('isNamespacePrefixAvailable')),
        dataNotAvailableMessage:"You have not created/modified any Templates.",
        queryForAll:"select id, "+readCookie('NamespacePrefix')+"Active__c, "+readCookie('NamespacePrefix')+"Version__c , Name, LastModifiedDate, LastModifiedBy.Id, CreatedBy.Name, LastModifiedBy.Name from "+readCookie('NamespacePrefix')+"VlocityUITemplate__c order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, "+readCookie('NamespacePrefix')+"Active__c, "+readCookie('NamespacePrefix')+"Version__c , Name, LastModifiedDate, LastModifiedBy.Id, CreatedBy.Name, LastModifiedBy.Name from "+readCookie('NamespacePrefix')+"VlocityUITemplate__c where name like ",
        query:"select id, "+readCookie('NamespacePrefix')+"Active__c, "+readCookie('NamespacePrefix')+"Version__c , Name, LastModifiedDate, LastModifiedBy.Id, CreatedBy.Name, LastModifiedBy.Name from "+readCookie('NamespacePrefix')+"VlocityUITemplate__c where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc ",
        metadata:"VlocityUITemplate__c",
        type:"table",
        headers:["Edit", "Download", "Name"],
        imagesrc : chrome.runtime.getURL("/img/icons/triggers.png"),
        fieldlevelactions:[{name:"ViewEye"}],
        objectlevelaction:[
            {name:"New", actionUrl:"/apex/"+readCookie('NamespacePrefix')+"uitemplatedesigner"},
            {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"},
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/apex/"+readCookie('NamespacePrefix')+"TemplateHome",
        midurl:"/apex/"+readCookie('NamespacePrefix')+"uitemplatedesigner?id=",
        placeholderText:"Quick find/search Templates..."
    },{
        label:"Cards",
        value:"VlocityUILayout__c",
        tooltipMessage:"Open Developer Console",
        isSearchable:true,
        formainmenu:true,
		technologyFeature:"Vlocity",
        eligibleForPackageXml:false,
        EligibleForAdvanceSearch:true,
        visibleForMetadataMenu:Boolean(readCookie('isNamespacePrefixAvailable')),
        visibleForMetadataIconMenu:Boolean(readCookie('isNamespacePrefixAvailable')),
        dataNotAvailableMessage:"You have not created/modified any Cards.",
        menuname:"favourite",
        queryForAll:"select id, "+readCookie('NamespacePrefix')+"Active__c, "+readCookie('NamespacePrefix')+"Version__c , Name, LastModifiedDate, LastModifiedBy.Id, CreatedBy.Name, LastModifiedBy.Name FROM "+readCookie('NamespacePrefix')+"VlocityUILayout__c order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, "+readCookie('NamespacePrefix')+"Active__c, "+readCookie('NamespacePrefix')+"Version__c , Name, LastModifiedDate, LastModifiedBy.Id, CreatedBy.Name, LastModifiedBy.Name FROM "+readCookie('NamespacePrefix')+"VlocityUILayout__c where Name like ",
        query:"select id, "+readCookie('NamespacePrefix')+"Active__c, "+readCookie('NamespacePrefix')+"Version__c , Name, LastModifiedDate, LastModifiedBy.Id, CreatedBy.Name, LastModifiedBy.Name FROM "+readCookie('NamespacePrefix')+"VlocityUILayout__c where  LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc",
        metadata:"VlocityUILayout__c",
        imagesrc : chrome.runtime.getURL("/img/icons/AuraDefinitionBundles.png"),
        type:"table",
        headers:[],
        fieldlevelactions:[{name:"ViewEye"}],
        objectlevelaction:[
                {name:"New", actionUrl:"/apex/"+readCookie('NamespacePrefix')+"carddesignernew"},
                {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"},
                {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/apex/"+readCookie('NamespacePrefix')+"cardhome",
        midurl:"/apex/"+readCookie('NamespacePrefix')+"carddesignernew?id=",
        placeholderText:"Quick find/search Cards..."
    },{
        label:"DataRaptor",
        value:"DRBundle__c",
        tooltipMessage:"View all DataRaptors on salesforce",
        isSearchable:true,
        formainmenu:true,
		technologyFeature:"Vlocity",
        eligibleForPackageXml:false,
        EligibleForAdvanceSearch:true,
        visibleForMetadataMenu:Boolean(readCookie('isNamespacePrefixAvailable')),
        visibleForMetadataIconMenu:Boolean(readCookie('isNamespacePrefixAvailable')),
        dataNotAvailableMessage:"You have not created/modified any DataRaptor.",
        menuname:"favourite",
        queryForAll:"select id,  Name, LastModifiedDate, LastModifiedBy.Id, CreatedBy.Name, LastModifiedBy.Name from "+readCookie('NamespacePrefix')+"DRBundle__c order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, Name, LastModifiedDate, LastModifiedBy.Id, CreatedBy.Name, LastModifiedBy.Name from "+readCookie('NamespacePrefix')+"DRBundle__c where name like ",
        query:"select id, Name, LastModifiedDate, LastModifiedBy.Id, CreatedBy.Name, LastModifiedBy.Name from "+readCookie('NamespacePrefix')+"DRBundle__c where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc ",
        metadata:"DRBundle__c",
        type:"table",
        imagesrc : chrome.runtime.getURL("/img/icons/pages.png"),
        headers:["Edit", "Security", "Name"],
        fieldlevelactions:[{name:"ViewEye"}],
        objectlevelaction:[ 
	        {name:"New", actionUrl:"/apex/"+readCookie('NamespacePrefix')+"drmapper"}, 
	        {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
	        {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
	        ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/apex/"+readCookie('NamespacePrefix')+"DRHome",
        midurl:"/apex/"+readCookie('NamespacePrefix')+"drmapper?id=",
        placeholderText:"Quick find/search Data Raptors..."
    },{
        label:"Actions",
        value:"VlocityAction__c",
        tooltipMessage:"View all Actions on salesforce",
        isSearchable:true,
        formainmenu:true,
		technologyFeature:"Vlocity",
        EligibleForAdvanceSearch:true,
        menuname:"favourite",
        eligibleForPackageXml:false,
        visibleForMetadataMenu:Boolean(readCookie('isNamespacePrefixAvailable')),
        dataNotAvailableMessage:"You have not created/modified any Vlocity Actions.",
        queryForAll:"select id, "+readCookie('NamespacePrefix')+"IsActive__c, "+readCookie('NamespacePrefix')+"DisplayLabel__c, "+readCookie('NamespacePrefix')+"CustomLabelName__c, name, createdby.Name, LastModifiedBy.Name from "+readCookie('NamespacePrefix')+"VlocityAction__c order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, "+readCookie('NamespacePrefix')+"DisplayLabel__c, "+readCookie('NamespacePrefix')+"CustomLabelName__c, "+readCookie('NamespacePrefix')+"IsActive__c,  name, createdby.Name, LastModifiedBy.Name from "+readCookie('NamespacePrefix')+"VlocityAction__c where Name like ",
        query:"select id, "+readCookie('NamespacePrefix')+"IsActive__c, "+readCookie('NamespacePrefix')+"DisplayLabel__c, "+readCookie('NamespacePrefix')+"CustomLabelName__c, name, createdby.Name, LastModifiedBy.Name from "+readCookie('NamespacePrefix')+"VlocityAction__c where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc ",
        metadata:"VlocityAction__c",
        type:"table",
        headers:["Edit", "Name"],
        imagesrc : chrome.runtime.getURL("/img/icons/objects.png"),
        fieldlevelactions:[
				{name:"ViewEye"},
                {name:"Edit", actionUrl:"/e"}],
        objectlevelaction:[
			{name:"New", actionUrl:"/a6j/e"}, 
	        {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
	        {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
	        ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/a6j",
        midurl:"",
        placeholderText:"Quick find/search Vlocity Actions..."
    },{
        label:"Doc Template",
        value:"DocumentTemplate__c",
        tooltipMessage:"View all Document Templates on salesforce",
        isSearchable:true,
        formainmenu:true,
		technologyFeature:"Vlocity",
        EligibleForAdvanceSearch:true,
        menuname:"favourite",
        eligibleForPackageXml:false,
        visibleForMetadataMenu:Boolean(readCookie('isNamespacePrefixAvailable')),
        dataNotAvailableMessage:"You have not created/modified any Document Templates.",
        queryForAll:"select id, "+readCookie('NamespacePrefix')+"IsActive__c,  name, createdby.Name, LastModifiedBy.Name from "+readCookie('NamespacePrefix')+"DocumentTemplate__c order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, "+readCookie('NamespacePrefix')+"IsActive__c,  name, createdby.Name, LastModifiedBy.Name from "+readCookie('NamespacePrefix')+"DocumentTemplate__c where Name like ",
        query:"select id, "+readCookie('NamespacePrefix')+"IsActive__c,  name, createdby.Name, LastModifiedBy.Name from "+readCookie('NamespacePrefix')+"DocumentTemplate__c where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc ",
        metadata:"DocumentTemplate__c",
        type:"table",
        headers:["Edit", "Name"],
        imagesrc : chrome.runtime.getURL("/img/icons/objects.png"),
        fieldlevelactions:[
				{name:"ViewEye"}],
        objectlevelaction:[
			{name:"New", actionUrl:"/apex/"+readCookie('NamespacePrefix')+"documenttemplate"}, 
	        {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
	        {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
	        ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/apex/"+readCookie('NamespacePrefix')+"DocTemplateList",
        midurl:"apex/"+readCookie('NamespacePrefix')+"documenttemplate?templateId=",
        placeholderText:"Quick find/search doc templates..."
    },{
        label:"Products",
        value:"Product2",
        tooltipMessage:"View all Products on salesforce",
        queryForAll:"select id, IsActive, name, "+readCookie('NamespacePrefix')+"Status__c, createdby.Name, LastModifiedBy.Name from Product2 order by LastModifiedDate desc",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
		technologyFeature:"Vlocity",
        visibleForMetadataMenu:Boolean(readCookie('isNamespacePrefixAvailable')),
        dataNotAvailableMessage:"You have not created/modified any products.",
        queryForAllWithWhere:"select id, IsActive, name, "+readCookie('NamespacePrefix')+"Status__c, createdby.Name, LastModifiedBy.Name from Product2 where name like ",
        query:"select id, Name, IsActive, createdby.name, "+readCookie('NamespacePrefix')+"Status__c, LastModifiedDate, LastModifiedBy.Name from Product2 where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc ",
        metadata:"Product2",
        headers:["Edit", "Name"],
        type:"table",
        fieldlevelactions:[{name:"ViewEye"},{name:"Edit", actionUrl:"/e"}],
        objectlevelaction:[{name:"New", actionUrl:"/01t/e"}, 
            {name:"Product Console", actionUrl:"/apex/"+readCookie('NamespacePrefix')+"VlocityIndustryConsole"}, 
            {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/01t",
        imagesrc : chrome.runtime.getURL("/img/icons/workflows.png"),
        midurl:"",
        placeholderText:"Quick find/search products..."
    },{
        label:"Launcher",
        value:"VlocitySearchWidgetSetup__c",
        tooltipMessage:"View all Interaction Launcher on salesforce",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
		technologyFeature:"Vlocity",
        visibleForMetadataMenu:Boolean(readCookie('isNamespacePrefixAvailable')),
        dataNotAvailableMessage:"You have not created/modified any Interaction Launcher.",
        queryForAll:"select id, "+readCookie('NamespacePrefix')+"IsActive__c,  name, createdby.Name, LastModifiedBy.Name from "+readCookie('NamespacePrefix')+"VlocitySearchWidgetSetup__c order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, "+readCookie('NamespacePrefix')+"IsActive__c,  name, createdby.Name, LastModifiedBy.Name from "+readCookie('NamespacePrefix')+"VlocitySearchWidgetSetup__c where name like ",
        query:"select id, "+readCookie('NamespacePrefix')+"IsActive__c, name, createdby.Name, LastModifiedBy.Name from "+readCookie('NamespacePrefix')+"VlocitySearchWidgetSetup__c where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc ",
        metadata:"VlocitySearchWidgetSetup__c",
        type:"table",
        headers:["Edit", "Name"],
        fieldlevelactions:[{name:"ViewEye"},{name:"Edit", actionUrl:"/e"}],
        imagesrc : chrome.runtime.getURL("/img/icons/components.png"),
        objectlevelaction:[{name:"New", actionUrl:"/a6x/e"},
         {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
         {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
         ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/a6x",
        midurl:"",
        placeholderText:"Quick find/search Interaction Launcher..."
    },{
        label:"Attribute",
        value:"Attribute__c",
        tooltipMessage:"View all attributes on salesforce",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        menuname:"favourite",
        eligibleForPackageXml:false,
		technologyFeature:"Vlocity",
        visibleForMetadataMenu:Boolean(readCookie('isNamespacePrefixAvailable')),
        dataNotAvailableMessage:"You have not created/modified any attribute.",
        queryForAll:"select id, "+readCookie('NamespacePrefix')+"ActiveFlg__c,  name, createdby.Name, LastModifiedBy.Name from "+readCookie('NamespacePrefix')+"Attribute__c order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, "+readCookie('NamespacePrefix')+"ActiveFlg__c,  name, createdby.Name, LastModifiedBy.Name from "+readCookie('NamespacePrefix')+"Attribute__c where Name like ",
        query:"select id, "+readCookie('NamespacePrefix')+"ActiveFlg__c,  name, createdby.Name, LastModifiedBy.Name from "+readCookie('NamespacePrefix')+"Attribute__c where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc ",
        metadata:"Attribute__c",
        type:"table",
        imagesrc : chrome.runtime.getURL("/img/icons/fields.png"),
        headers:["Edit", "Name"],
        fieldlevelactions:[
				{name:"ViewEye"},
                {name:"Edit", actionUrl:"/e"}],
        objectlevelaction:[{name:"New", actionUrl:"/a36/e"},{name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"},
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
            
        ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/a36",
        midurl:"",
        placeholderText:"Quick find/search Attribute..."
    },{
        label:"Matrices",
        value:"CalculationMatrix__c",
        tooltipMessage:"View all CalculationMatrices on salesforce",
        isSearchable:true,
        formainmenu:true,
        EligibleForAdvanceSearch:true,
		technologyFeature:"Vlocity",
        eligibleForPackageXml:false,
        visibleForMetadataMenu:Boolean(readCookie('isNamespacePrefixAvailable')),
        dataNotAvailableMessage:"You have not created/modified any Calculation Matrices.",
        queryForAll:"select id,  name, createdby.Name, LastModifiedBy.Name from "+readCookie('NamespacePrefix')+"CalculationMatrix__c order by LastModifiedDate desc",
        queryForAllWithWhere:"select id,  name, createdby.Name, LastModifiedBy.Name from "+readCookie('NamespacePrefix')+"CalculationMatrix__c where name like ",
        query:"select id,  name, createdby.Name, LastModifiedBy.Name from "+readCookie('NamespacePrefix')+"CalculationMatrix__c where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc ",
        metadata:"CalculationMatrix__c",
        type:"table",
        headers:["Edit", "Name"],
        fieldlevelactions:[{name:"ViewEye"},{name:"Edit", actionUrl:"/e"}],
        objectlevelaction:[{name:"New", actionUrl:"/a3H/e"}, 
	        {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
	        {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
	        ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        imagesrc : chrome.runtime.getURL("/img/icons/labels.png"),
        listUrl:"/a3H",
        midurl:"",
        placeholderText:"Quick find/search Calculation Matrices..."
    },{
        label:"Classes",
        value:"Classes",
        isSearchable:true,
        formainmenu:true,
		technologyFeature:"Salesforce",
        tooltipMessage:"View all classes on salesforce",
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:true,
        visibleForMetadataMenu:true,
        visibleForMetadataIconMenu:true,
        dataNotAvailableMessage:"You have not created/modified any class.",
        menuname:"favourite",
        queryForAll:"select id, name,  ApiVersion, createdby.Name, IsValid, NamespacePrefix, LastModifiedBy.Name from ApexClass WHERE ManageableState != 'installed' order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, name, ApiVersion, IsValid,createdby.Name, NamespacePrefix, LastModifiedBy.Name from ApexClass WHERE  ManageableState != 'installed' AND name like ",
        query:"SELECT Id, Name, LastModifiedDate, LastModifiedBy.Id,  IsValid, ApiVersion, NamespacePrefix, CreatedBy.Name, LastModifiedBy.Name FROM ApexClass WHERE  ManageableState != 'installed' AND (LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"') order by LastModifiedDate desc",
        metadata:"ApexClass",
        imagesrc : chrome.runtime.getURL("/img/icons/classes.png"),
        type:"table",
        headers:["Edit", "Download", "Name"],
        fieldlevelactions:[
                {name:"Edit", actionUrl:"/e"},
                {name:"Download", actionUrl:"/setup/apexcodedownload?class_id="}
                ],
        objectlevelaction:[
            {name:"New", actionUrl:"https://"+window.location.host+"/setup/build/editApexClass.apexp"},
            {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"},
            {name:"Generate WSDL", actionUrl:"/_ui/common/api/callout/ui/Wsdl2ApexStageManager"}, 
            {name:"Schedule Apex", actionUrl:"/ui/setup/apex/batch/ScheduleBatchApexPage"}],
            url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/01p",
        url:"https://"+window.location.host+"/services/data/v60.0/tooling/query/?q=",
        midurl:"",
        placeholderText:"Quick find/search class..."
    },{
        label:"Triggers",
        value:"Triggers",
        tooltipMessage:"View all triggers on salesforce",
        isSearchable:true,
        formainmenu:true,
        EligibleForAdvanceSearch:true,
        menuname:"favourite",
		technologyFeature:"Salesforce",
        eligibleForPackageXml:true,
        visibleForMetadataMenu:true,
        visibleForMetadataIconMenu:true,
        dataNotAvailableMessage:"You have not created/modified any triggers.",
        queryForAll:"select id,name, ApiVersion, createdby.Name, NamespacePrefix, LastModifiedBy.Name from ApexTrigger WHERE ManageableState != 'installed' order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, name, ApiVersion, createdby.Name, NamespacePrefix, LastModifiedBy.Name from ApexTrigger where  ManageableState != 'installed' AND name like ",
        query:"select id, Name, ApiVersion, createdby.name, LastModifiedDate, NamespacePrefix, LastModifiedBy.Name from ApexTrigger where  ManageableState != 'installed' AND (LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"') order by LastModifiedDate desc ",
        metadata:"ApexTrigger",
        type:"table",
        headers:["Edit", "Download", "Name"],
        imagesrc : chrome.runtime.getURL("/img/icons/triggers.png"),
        fieldlevelactions:[
                {name:"Edit", actionUrl:"/e"}, 
                {name:"Download", actionUrl:"/setup/apexcodedownload?class_id="}
                ],
        objectlevelaction:[
            {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"},
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/tooling/query/?q=",
        listUrl:"/setup/build/allTriggers.apexp",
        midurl:"",
        placeholderText:"Quick find/search triggers..."
    },{
        label:"LWC",
        value:"LightningComponentBundle",
        tooltipMessage:"View all lightning components",
        isSearchable:true,
        formainmenu:false,
        eligibleForPackageXml:true,
        EligibleForAdvanceSearch:true,
        visibleForMetadataMenu:true,
		technologyFeature:"Salesforce",
        dataNotAvailableMessage:"You have not created/modified any LWC components.",
        menuname:"favourite",
        queryForAll:"SELECT Id, DeveloperName, LastModifiedBy.Name, NamespacePrefix FROM LightningComponentBundle WHERE ManageableState != 'installed' order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, DeveloperName, LastModifiedBy.Name, NamespacePrefix FROM LightningComponentBundle where  ManageableState != 'installed' AND DeveloperName like ",
        query:"SELECT Id, DeveloperName, LastModifiedBy.Name, NamespacePrefix FROM LightningComponentBundle where  ManageableState != 'installed' AND (LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"') order by LastModifiedDate desc",
        metadata:"LightningComponentBundle",
        imagesrc : chrome.runtime.getURL("/img/icons/AuraDefinitionBundles.png"),
        type:"table",
        headers:[],
        fieldlevelactions:[],
        objectlevelaction:[
                {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"},
                {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
                
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/tooling/query/?q=",
        listUrl:"/ui/aura/impl/setup/LightningComponentListPage",
        midurl:"",
        placeholderText:"Quick find/search lwc components..."
    },{
        label:"Aura Definition",
        value:"AuraDefinitionBundle",
        tooltipMessage:"View all lightning components",
        isSearchable:true,
        formainmenu:true,
        eligibleForPackageXml:true,
        EligibleForAdvanceSearch:true,
        visibleForMetadataMenu:true,
		technologyFeature:"Salesforce",
        dataNotAvailableMessage:"You have not created/modified any lightening components.",
        menuname:"favourite",
        queryForAll:"SELECT Id, DeveloperName, LastModifiedBy.Name, NamespacePrefix FROM AuraDefinitionBundle WHERE  ManageableState != 'installed' order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, DeveloperName, LastModifiedBy.Name, NamespacePrefix FROM AuraDefinitionBundle where  ManageableState != 'installed' AND DeveloperName like ",
        query:"SELECT Id, DeveloperName, LastModifiedBy.Name, NamespacePrefix FROM AuraDefinitionBundle where  ManageableState != 'installed' AND (LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"') order by LastModifiedDate desc",
        metadata:"AuraDefinitionBundle",
        imagesrc : chrome.runtime.getURL("/img/icons/AuraDefinitionBundles.png"),
        type:"table",
        headers:[],
        fieldlevelactions:[],
        objectlevelaction:[
                {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"},
                {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
                
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/tooling/query/?q=",
        listUrl:"/ui/aura/impl/setup/LightningComponentListPage",
        midurl:"",
        placeholderText:"Quick find/search aura components..."
    },{
        label:"Pages",
        value:"Pages",
        tooltipMessage:"View all pages on salesforce",
        isSearchable:true,
        formainmenu:true,
        eligibleForPackageXml:true,
        EligibleForAdvanceSearch:true,
        visibleForMetadataMenu:true,
		technologyFeature:"Salesforce",
        visibleForMetadataIconMenu:false,
        dataNotAvailableMessage:"You have not created/modified any visualforce pages.",
        menuname:"favourite",
        queryForAll:"select id, name, ApiVersion, createdby.Name, NamespacePrefix, LastModifiedBy.Name from ApexPage WHERE ManageableState != 'installed' order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, name, ApiVersion, NamespacePrefix, createdby.Name, LastModifiedBy.Name from ApexPage where  ManageableState != 'installed' AND Name like ",
        query:"select id, Name, ApiVersion, createdby.name, NamespacePrefix, LastModifiedDate, LastModifiedBy.Name from ApexPage where  ManageableState != 'installed' AND (LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"') order by LastModifiedDate desc ",
        metadata:"ApexPage",
        type:"table",
        imagesrc : chrome.runtime.getURL("/img/icons/pages.png"),
        headers:["Edit", "Security", "Name"],
        fieldlevelactions:[
                        {name:"Edit", actionUrl:"/e"}
                        ],
        objectlevelaction:[{name:"New", actionUrl:"https://"+window.location.host+"/066/e"}, 
	        {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
	        {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
	        ],
        url:"https://"+window.location.host+"/services/data/v60.0/tooling/query/?q=",
        listUrl:"/apexpages/setup/listApexPage.apexp",
        midurl:"",
        placeholderText:"Quick find/search pages..."
    },{
        label:"Components",
        value:"Components",
        tooltipMessage:"View all components on salesforce",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:true,
		technologyFeature:"Salesforce",
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any visualforce components.",
        queryForAll:"select id, name, createdby.Name, NamespacePrefix, LastModifiedBy.Name from ApexComponent WHERE  ManageableState != 'installed' order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, name, createdby.Name, NamespacePrefix, LastModifiedBy.Name from ApexComponent WHERE  ManageableState != 'installed' AND Name like ",
        query:"select id, Name, createdby.name, LastModifiedDate, NamespacePrefix, LastModifiedBy.Name from ApexComponent WHERE  ManageableState != 'installed' AND (LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"') order by LastModifiedDate desc ",
        metadata:"ApexComponent",
        type:"table",
        headers:["Edit", "Name"],
        fieldlevelactions:[{name:"Edit", actionUrl:"/e"}],
        imagesrc : chrome.runtime.getURL("/img/icons/components.png"),
        objectlevelaction:[{name:"New", actionUrl:"https://"+window.location.host+"/099/e"},
         {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
         {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
         ],
        url:"https://"+window.location.host+"/services/data/v60.0/tooling/query/?q=",
        listUrl:"/apexpages/setup/listApexComponent.apexp",
        midurl:"",
        placeholderText:"Quick find/search components..."
    },{
        label:"Objects",
        value:"Objects",
        tooltipMessage:"View all objects on salesforce",
        isSearchable:true,
        formainmenu:true,
        EligibleForAdvanceSearch:true,
        menuname:"favourite",
        eligibleForPackageXml:true,
        visibleForMetadataMenu:true,
		technologyFeature:"Salesforce",
        visibleForMetadataIconMenu:true,
        dataNotAvailableMessage:"You have not created/modified any custom objects.",
        queryForAll:"select id, DeveloperName, ExternalName, createdby.Name, LastModifiedBy.Name, NamespacePrefix from CustomObject WHERE ManageableState != 'installed' order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, DeveloperName, ExternalName, createdby.Name, NamespacePrefix, LastModifiedBy.Name from CustomObject where  ManageableState != 'installed' AND DeveloperName like ",
        query:"select id, DeveloperName, createdby.name, ExternalName, LastModifiedDate, NamespacePrefix, LastModifiedBy.Name from CustomObject where  ManageableState != 'installed' AND (LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"') order by LastModifiedDate desc ",
        metadata:"CustomObjects",
        type:"table",
        headers:["Edit", "Name"],
        imagesrc : chrome.runtime.getURL("/img/icons/objects.png"),
        fieldlevelactions:[
                {name:"Edit", actionUrl:"/e"}],
        objectlevelaction:[{name:"New", actionUrl:"https://"+window.location.host+"/01I/e"}, 
	        {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
	        {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
	        ],
        url:"https://"+window.location.host+"/services/data/v60.0/tooling/query/?q=",
        listUrl:"/p/setup/custent/CustomObjectsPage",
        midurl:"",
        placeholderText:"Quick find/search objects..."
    },{
        label:"Fields",
        value:"Fields",
        tooltipMessage:"View all objects on salesforce",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        menuname:"favourite",
        eligibleForPackageXml:true,
        visibleForMetadataMenu:true,
		technologyFeature:"Salesforce",
        dataNotAvailableMessage:"You have not created/modified any custom fields.",
        queryForAll:"select id, DeveloperName, createdby.Name, TableEnumOrId, NamespacePrefix, LastModifiedBy.Name from CustomField WHERE  ManageableState != 'installed' order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, DeveloperName, createdby.Name, TableEnumOrId, NamespacePrefix, LastModifiedBy.Name from CustomField where  ManageableState != 'installed' AND DeveloperName like ",
        query:"select id, DeveloperName, createdby.name, LastModifiedDate, TableEnumOrId, NamespacePrefix, LastModifiedBy.Name from CustomField where  ManageableState != 'installed' AND (LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"') order by LastModifiedDate desc ",
        metadata:"CustomFields",
        type:"table",
        imagesrc : chrome.runtime.getURL("/img/icons/fields.png"),
        headers:["Edit", "Name"],
        fieldlevelactions:[
                {name:"Edit", actionUrl:"/e"}],
        objectlevelaction:[{name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"},
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
            
        ],
        url:"https://"+window.location.host+"/services/data/v60.0/tooling/query/?q=",
        listUrl:"/p/setup/custent/CustomObjectsPage",
        midurl:"",
        placeholderText:"Quick find/search fields..."
    },{
        label:"Labels",
        value:"Labels",
        tooltipMessage:"View all labels on salesforce",
        isSearchable:true,
        formainmenu:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:true,
        visibleForMetadataMenu:true,
        visibleForMetadataIconMenu:true,
		technologyFeature:"Salesforce",
        dataNotAvailableMessage:"You have not created/modified any custom labels.",
        queryForAll:"select id, name, createdby.Name, LastModifiedBy.Name, NamespacePrefix from CustomLabel WHERE  ManageableState != 'installed' order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, name, createdby.Name, NamespacePrefix, LastModifiedBy.Name from CustomLabel where  ManageableState != 'installed' AND name like ",
        query:"select id, Name, createdby.name, LastModifiedDate, NamespacePrefix, LastModifiedBy.Name from CustomLabel where  ManageableState != 'installed' AND (LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"') order by LastModifiedDate desc ",
        metadata:"CustomLabel",
        type:"table",
        headers:["Edit", "Name"],
        fieldlevelactions:[{name:"Edit", actionUrl:"/e"}],
        objectlevelaction:[{name:"New", actionUrl:"https://"+window.location.host+"/101/e"}, 
	        {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
	        {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
	        ],
        url:"https://"+window.location.host+"/services/data/v60.0/tooling/query/?q=",
        imagesrc : chrome.runtime.getURL("/img/icons/labels.png"),
        listUrl:"/101",
        midurl:"",
        placeholderText:"Quick find/search labels..."
    },{
        label:"Workflows",
        value:"Workflows",
        tooltipMessage:"View all workflows on salesforce",
        queryForAll:"select id, name, createdby.Name, LastModifiedBy.Name from WorkflowRule order by LastModifiedDate desc",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:true,
        visibleForMetadataMenu:true,
		technologyFeature:"Salesforce",
        dataNotAvailableMessage:"You have not created/modified any workflows.",
        queryForAllWithWhere:"select id, name, createdby.Name, NamespacePrefix, LastModifiedBy.Name from WorkflowRule where  ManageableState != 'installed' AND name like ",
        query:"select id, Name, createdby.name, LastModifiedDate, NamespacePrefix, LastModifiedBy.Name from WorkflowRule where  ManageableState != 'installed' AND (LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"') order by LastModifiedDate desc ",
        metadata:"WorkflowRule",
        headers:["Edit", "Name"],
        type:"table",
        fieldlevelactions:[{name:"Edit", actionUrl:"/e"}, {name:"cloneWF", actionUrl:"/e"}],
        objectlevelaction:[{name:"New", actionUrl:"https://"+window.location.host+"/_ui/core/workflow/WorkflowSplashUi?EntityId=WorkflowRule&setupid=WorkflowRules"}, 
            {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/tooling/query/?q=",
        listUrl:"/_ui/core/workflow/WorkflowSplashUi?EntityId=WorkflowRule",
        imagesrc : chrome.runtime.getURL("/img/icons/workflows.png"),
        midurl:"",
        placeholderText:"Quick find/search workflow..."
    },{
        label:"Flows",
        value:"Flows",
        tooltipMessage:"View all flows on salesforce",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:true,
		technologyFeature:"Salesforce",
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any flows.",
        queryForAll:"select id, DeveloperName, createdby.Name, NamespacePrefix, LastModifiedBy.Name from FlowDefinition WHERE  ManageableState != 'installed' order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, DeveloperName, createdby.Name, NamespacePrefix, LastModifiedBy.Name from FlowDefinition where  ManageableState != 'installed' AND DeveloperName like ",
        query:"select id, DeveloperName, createdby.name, LastModifiedDate, NamespacePrefix, LastModifiedBy.Name from FlowDefinition where  ManageableState != 'installed' AND (LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"') order by LastModifiedDate desc ",
        metadata:"Flows",
        type:"table",
        headers:["Edit", "Name"],
        fieldlevelactions:[
                {name:"Edit", actionUrl:"/e"}
                ],
        objectlevelaction:[{name:"New", actionUrl:"https://"+window.location.host+"/designer/designer.apexp"}, 
            {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/tooling/query/?q=",
        imagesrc : chrome.runtime.getURL("/img/icons/flows.png"),
        listUrl:"/300",
        midurl:"",
        placeholderText:"Quick find/search flows..."
    },{
        label:"Email Templates",
        value:"EmailTemplates",
        tooltipMessage:"View all email templates on salesforce",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:true,
        visibleForMetadataMenu:true,
		technologyFeature:"Salesforce",
        dataNotAvailableMessage:"You have not created/modified any email templates.",
        queryForAll:"select id, name, ApiVersion, createdby.Name, NamespacePrefix,  LastModifiedBy.Name from EmailTemplate WHERE ManageableState != 'installed' order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, name, ApiVersion, createdby.Name, NamespacePrefix, LastModifiedBy.Name from EmailTemplate where  ManageableState != 'installed' AND name like ",
        query:"select id, Name, ApiVersion, createdby.name, LastModifiedDate, NamespacePrefix, LastModifiedBy.Name from EmailTemplate where  ManageableState != 'installed' AND (LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"') order by LastModifiedDate desc ",
        metadata:"EmailTemplates",
        type:"table",
        imagesrc : chrome.runtime.getURL("/img/icons/emailtemplates.png"),
        headers:["Edit", "Name"],
        fieldlevelactions:[
                {name:"Edit", actionUrl:"/e"}
                ],
        objectlevelaction:[{name:"New", actionUrl:"https://"+window.location.host+"/p/email/template/NewEmailTemplateStageManager?setupid=CommunicationTemplatesEmail"},
        {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/tooling/query/?q=",
        listUrl:"/00X",
        midurl:"",
        placeholderText:"Quick find/search email template..."
    },{
        label:"Users",
        value:"Users",
        tooltipMessage:"View all users on salesforce",
        isSearchable:true,
        forAdvanceSearchOnly:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:false,
		technologyFeature:"Salesforce",
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any users.",
        queryForAll:"select id, name, email, username, LastModifiedBy.Name from User where IsActive = true order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, name, email, username, LastModifiedBy.Name from User where IsActive = true and name like ",
        query:"select id, name, email, username, LastModifiedBy.Name from User where LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"' order by LastModifiedDate desc",
        metadata:"Users",
        type:"table",
        imagesrc : chrome.runtime.getURL("/img/icons/users.png"),
        headers:["Edit", "Name"],
        fieldlevelactions:[
                {name:"Edit", actionUrl:"/e"}
                ],
        objectlevelaction:[{name:"New", actionUrl:"https://"+window.location.host+"/005/e"}, 
        {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/005",
        midurl:"",
        placeholderText:"Quick find/search Users..."
    },{
        label:"Static Resource",
        value:"StaticResource",
        tooltipMessage:"View all static resources on salesforce",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:true,
		technologyFeature:"Salesforce",
        visibleForMetadataMenu:true,
        dataNotAvailableMessage:"You have not created/modified any static resource.",
        queryForAll:"select id, name, LastModifiedBy.Name, NamespacePrefix from StaticResource WHERE  ManageableState != 'installed' order by LastModifiedDate desc",
        queryForAllWithWhere:"select id, name, NamespacePrefix, LastModifiedBy.Name from StaticResource where  ManageableState != 'installed' AND name like ",
        query:"select id, name, NamespacePrefix, LastModifiedBy.Name from StaticResource where  ManageableState != 'installed' AND (LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"') order by LastModifiedDate desc",
        metadata:"StaticResource",
        type:"table",
        headers:["Edit", "Name"],
        imagesrc : chrome.runtime.getURL("/img/icons/staticresource.png"),
        fieldlevelactions:[
                {name:"Edit", actionUrl:"/e"}
                ],
        objectlevelaction:[{name:"New", actionUrl:"https://"+window.location.host+"/081/e"},
        {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/tooling/query/?q=",
        listUrl:"/081",
        midurl:"",
        placeholderText:"Quick find/search Resource..."
    },{
        label:"Profile",
        value:"Profile",
        tooltipMessage:"View all profiles on salesforce",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        visibleForMetadataMenu:true,
		technologyFeature:"Salesforce",
        eligibleForPackageXml:true,
        dataNotAvailableMessage:"You have not created/modified any profile.",
        queryForAll:"SELECT Id, Name, LastModifiedBy.name FROM Profile order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, Name, LastModifiedBy.name FROM Profile where name like ",
        query:"SELECT Id, Name, LastModifiedBy.name FROM Profile where (LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"') order by LastModifiedDate desc",
        metadata:"Profile",
        type:"table",
        headers:["Edit", "Clone", "Name"],
        fieldlevelactions:[
                {name:"Edit", actionUrl:"/e"},
                {name:"Clone", actionUrl:"/_ui/perms/ui/profile/ProfileClone/e?id="}
                ],
        objectlevelaction:[{name:"New", actionUrl:"https://"+window.location.host+"/_ui/perms/ui/profile/ProfileClone/e"},
        {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/tooling/query/?q=",
        listUrl:"/00e",
        midurl:"",
        placeholderText:"Quick find/search Profile..."
    },{
        label:"Permission Set",
        value:"PermissionSet",
        tooltipMessage:"View all permission set on salesforce",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        visibleForMetadataMenu:true,
		technologyFeature:"Salesforce",
        eligibleForPackageXml:true,
        dataNotAvailableMessage:"You have not created/modified any permission set.",
        queryForAll:"SELECT Id, Label, Name, LastModifiedBy.name FROM PermissionSet WHERE ManageableState != 'installed' order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, Label, Name, LastModifiedBy.name FROM PermissionSet where ManageableState != 'installed' AND name like ",
        query:"SELECT Id, Label, Name, LastModifiedBy.name FROM PermissionSet where ManageableState != 'installed' AND (LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"') order by LastModifiedDate desc",
        metadata:"PermissionSet",
        type:"table",
        headers:["Edit", "Clone", "Name"],
        fieldlevelactions:[
                {name:"Edit", actionUrl:"/e"},
                {name:"Clone", actionUrl:"/udd/PermissionSet/newPermissionSet.apexp?id="}
                ],
        objectlevelaction:[{name:"New", actionUrl:"https://"+window.location.host+"/udd/PermissionSet/newPermissionSet.apexp"},
        {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/tooling/query/?q=",
        listUrl:"/0PS",
        midurl:"",
        placeholderText:"Quick find/search permission set..."
    },{
        label:"Perm Set Group",
        value:"PermissionSetGroup",
        tooltipMessage:"View all permission set group on salesforce",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        visibleForMetadataMenu:true,
		technologyFeature:"Salesforce",
        eligibleForPackageXml:true,
        dataNotAvailableMessage:"You have not created/modified any permission set.",
        queryForAll:"SELECT Id, DeveloperName, MasterLabel, LastModifiedBy.name FROM PermissionSetGroup WHERE ManageableState != 'installed' order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, DeveloperName, MasterLabel, LastModifiedBy.name FROM PermissionSetGroup where ManageableState != 'installed' AND name like ",
        query:"SELECT Id, DeveloperName, MasterLabel, LastModifiedBy.name FROM PermissionSetGroup where ManageableState != 'installed' AND (LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"') order by LastModifiedDate desc",
        metadata:"PermissionSetGroup",
        type:"table",
        headers:["Edit", "Clone", "Name"],
        fieldlevelactions:[
                {name:"Edit", actionUrl:"/e"}
                ],
        objectlevelaction:[{name:"New", actionUrl:"https://"+window.location.host+"/_ui/perms/ui/setup/PermSetGroupsPage"},
        {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/0PG",
        midurl:"",
        placeholderText:"Quick find/search permission set group..."
    },{
        label:"Group",
        value:"Group",
        tooltipMessage:"View all groups on salesforce",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:true,
		technologyFeature:"Salesforce",
        dataNotAvailableMessage:"You have not created/modified any group.",
        queryForAll:"SELECT Id, DeveloperName, LastModifiedBy.name FROM Group order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, DeveloperName, LastModifiedBy.name FROM Group where DeveloperName like ",
        query:"SELECT Id, DeveloperName, LastModifiedBy.name FROM Group where (LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"') order by LastModifiedDate desc",
        metadata:"Group",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        fieldlevelactions:[{}],
        midurl:"setup/own/groupdetail.jsp?id=",
        objectlevelaction:[{name:"New", actionUrl:"https://"+window.location.host+"/setup/own/groupedit.jsp"},
        {name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/p/own/OrgPublicGroupsPage/d",
        midurl:"setup/own/groupdetail.jsp?id=",
        placeholderText:"Quick find/search Group..."
    },{
        label:"Package.xml",
        value:"PackageXml",
        tooltipMessage:"Open home page",
        isSearchable:false,
		technologyFeature:"Salesforce",
        eligibleForPackageXml:false,
        visibleForMetadataMenu:false,
        url:"https://"+window.location.host+"/services/data/v60.0/tooling/query/?q=",
        midurl:"",
        listUrl:"/",
        fieldlevelactions:[{}],
        objectlevelaction:[
        					   {name:"Feedback", actionUrl:"https://chrome.google.com/webstore/detail/salesforce-simplified/hjeigbpcblpkaienmpihneipkempijob?hl=en"},
                               {name:"Report Issue", actionUrl:"https://github.com/rajnikantroy/SalesforceSimplified/issues/new"},
                               {name:"Blog", actionUrl:"https://salesforcsimplified.blogspot.com"}
                           ]
    },{
        label:"RecordType",
        value:"RecordType",
        tooltipMessage:"Go to home page",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:true,
        isSobjectType:true,
		technologyFeature:"Salesforce",
        dataNotAvailableMessage:"You have not created/modified any Record Type.",
        queryForAll:"SELECT Id, SobjectType, DeveloperName, LastModifiedBy.name FROM RecordType order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, SobjectType, DeveloperName, LastModifiedBy.name FROM RecordType where DeveloperName like ",
        query:"SELECT Id, DeveloperName, SobjectType, LastModifiedBy.name FROM RecordType where (LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"') order by LastModifiedDate desc",
        metadata:"RecordType",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        fieldlevelactions:[{name:"Edit", actionUrl:"/setup/ui/recordtypeedit.jsp?id="}],
        objectlevelaction:[{name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        midurl:"setup/ui/recordtypefields.jsp?id=",
        listUrl:"/",
        placeholderText:"Quick find/search Group..."
    },{
        label:"Layout",
        value:"Layout",
        tooltipMessage:"Go to home page",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
		technologyFeature:"Salesforce",
        eligibleForPackageXml:true,
        isSobjectType:true,
        dataNotAvailableMessage:"You have not created/modified any Layout",
        queryForAll:"SELECT Id, TableEnumOrId, Name, LastModifiedBy.name FROM Layout WHERE ManageableState != 'installed' order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, TableEnumOrId, Name, LastModifiedBy.name FROM Layout where ManageableState != 'installed' AND DeveloperName like ",
        query:"SELECT Id, TableEnumOrId, Name, LastModifiedBy.name FROM Layout where ManageableState != 'installed' AND (LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"') order by LastModifiedDate desc",
        metadata:"RecordType",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        fieldlevelactions:[],
        objectlevelaction:[{name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/tooling/query/?q=",
        midurl:"",
        listUrl:"/",
        placeholderText:"Quick find/search Group..."
    },{
        label:"AssignmentRule",
        value:"AssignmentRule",
        tooltipMessage:"Go to home page",
        isSearchable:true,
        isSobjectType:true,
        EligibleForAdvanceSearch:true,
		technologyFeature:"Salesforce",
        eligibleForPackageXml:true,
        dataNotAvailableMessage:"You have not created/modified any Assignment rules.",
        queryForAll:"SELECT Id, Name, SobjectType, LastModifiedBy.name FROM AssignmentRule order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, Name, SobjectType, LastModifiedBy.name FROM AssignmentRule where DeveloperName like ",
        query:"SELECT Id, Name, SobjectType, LastModifiedBy.name FROM AssignmentRule where (LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"') order by LastModifiedDate desc",
        metadata:"AssignmentRule",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        fieldlevelactions:[{name:"Edit", actionUrl:"/setup/own/entityruleedit.jsp?id="}],
        objectlevelaction:[{name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        midurl:"setup/own/entityruledetail.jsp?id=",
        listUrl:"/",
        placeholderText:"Quick find/search Group..."
    },{
        label:"WebLink",
        value:"WebLink",
        tooltipMessage:"Go to home page",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
		technologyFeature:"Salesforce",
        eligibleForPackageXml:true,
        isSobjectType:true,
        dataNotAvailableMessage:"You have not created/modified any Weblink.",
        queryForAll:"SELECT Id, Name, NamespacePrefix, LastModifiedBy.name FROM WebLink WHERE ManageableState != 'installed' order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, Name, NamespacePrefix, LastModifiedBy.name FROM WebLink where ManageableState != 'installed' AND DeveloperName like ",
        query:"SELECT Id, Name, LastModifiedBy.name, NamespacePrefix FROM WebLink where ManageableState != 'installed' AND (LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"') order by LastModifiedDate desc",
        metadata:"WebLink",
        type:"table",
        visibleForMetadataMenu:true,
        midurl:"",
        headers:["Edit", "Name"],
        fieldlevelactions:[{name:"Edit", actionUrl:"/e"}],
        objectlevelaction:[{name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/tooling/query/?q=",
        listUrl:"/",
        placeholderText:"Quick find/search Group..."
    },{
        label:"ListView",
        value:"ListView",
        tooltipMessage:"Go to home page",
        isSearchable:true,
        EligibleForAdvanceSearch:true,
        eligibleForPackageXml:true,
		technologyFeature:"Salesforce",
        isSobjectType:true,
        dataNotAvailableMessage:"You have not created/modified any Listview.",
        queryForAll:"SELECT Id, DeveloperName, SobjectType, NamespacePrefix, LastModifiedBy.name FROM ListView order by LastModifiedDate desc",
        queryForAllWithWhere:"SELECT Id, SobjectType, DeveloperName, NamespacePrefix, LastModifiedBy.name FROM ListView where DeveloperName like ",
        query:"SELECT Id, DeveloperName, SobjectType, LastModifiedBy.name, NamespacePrefix FROM ListView where (LastModifiedById='"+UserId.id+"' or CreatedById='"+UserId.id+"') order by LastModifiedDate desc",
        metadata:"WebLink",
        type:"table",
        visibleForMetadataMenu:true,
        headers:["Edit", "Name"],
        midurl:"",
        fieldlevelactions:[{}],
        objectlevelaction:[{name:"Setup", actionUrl:"/setup/forcecomHomepage.apexp?setupid=ForceCom"}, 
            {name:"Developer Console", actionUrl:"/_ui/common/apex/debug/ApexCSIPage"}
            ],
        url:"https://"+window.location.host+"/services/data/v60.0/query/?q=",
        listUrl:"/",
        placeholderText:"Quick find/search Group..."
    },{
        label:"Launcher Color",
        value:"LauncherColor",
        tooltipMessage:"Simplified Launcher Color",
        isSearchable:false,
        eligibleForPackageXml:false,
        url:"",
        visibleForMetadataMenu:true,
        listUrl:"/",
		technologyFeature:"Settings",
        fieldlevelactions:[{}],
        objectlevelaction:[
			   {name:"Feedback", actionUrl:"https://chrome.google.com/webstore/detail/salesforce-simplified/hjeigbpcblpkaienmpihneipkempijob?hl=en"},
               {name:"Report Issue", actionUrl:"https://github.com/rajnikantroy/SalesforceSimplified/issues/new"},
               {name:"Blog", actionUrl:"https://salesforcsimplified.blogspot.com"}
           ]
    }];
}]);